name: Android CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
              java-version: 11
              java-package: jdk
              architecture: x64

        - name: Resolve dependencies
          run: ./gradlew dependencies

        - name: Build with Gradle
          run: ./gradlew assembleRelease

        - name: Run all unit tests
          run: ./gradlew test

        - name: Kotlin lint
          run: ./gradlew ktlintCheck

    instrumented-test:
        runs-on: macos-latest
        strategy:
            matrix:
                api-level: [21, 26, 29]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11
                java-package: jdk
                architecture: x64

            - name: Gradle cache
              uses: actions/cache@v2
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
                key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

            - name: AVD cache
              uses: actions/cache@v2
              id: avd-cache
              with:
                path: |
                  ~/.android/avd/*
                  ~/.android/adb*
                key: avd-sdk${{ matrix.api-level }}

            - name: Create AVDs
              if: steps.avd-cache.outputs.cache-hit != 'true'
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: ${{ matrix.api-level }}
                arch: x86_64
                target: default
                ram-size: 2048M
                force-avd-creation: false
                emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                disable-animations: false
                script: echo "Generated AVD snapshot for caching."

            - name: Run all instrumented tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: ${{ matrix.api-level }}
                arch: x86_64
                target: default
                ram-size: 2048M
                force-avd-creation: false
                emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                disable-animations: true
                script: ./gradlew connectedCheck
